/* exported asin */
var sin = Math.sin;
var cos = Math.cos;
var sqrt = Math.sqrt;
var floor = Math.floor;
var pow = Math.pow;
var fabs = Math.abs;
var acos = Math.acos;
var asin = Math.asin;
var atan = Math.atan;
